language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t mengzhou44/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mengzhou44/docker-react npm run test
